### ISSUE TITLE
README: install jupyter or jupyterlab ot go to Operate First and spawn this image, etc etc

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/socrates#20]
Write install/run documentation

```
You can describe that in the README: install jupyter or jupyterlab ot go to Operate First and spawn this image, etc etc, but I feel it should not be part of that.
```
_Originally posted by @pacospace in https://github.com/thoth-station/socrates/pull/10#discussion_r691885062_

**Comment by xtuchyna** [comment]
/reopen
/remove-lifecycle rotten

hey @goern , what about this project? (seems that there are no people to maintain it, currently)

**Comment by goern** [comment]
this seems to be something we can achieve by using the ps-* pattern, so creating a repo with a Pipfile and having Kebechet maintain it, having aicoe-ci deliver the image to quay and make it part of ODH@op1st ?
